// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiV5yKHSWFklwzjU5t0VNh2HnpxWAPFFo',
    appId: '1:694407226020:web:d39ec13797b7a5259dbc31',
    messagingSenderId: '694407226020',
    projectId: 'college-notice-ee7ad',
    authDomain: 'college-notice-ee7ad.firebaseapp.com',
    storageBucket: 'college-notice-ee7ad.appspot.com',
    measurementId: 'G-0P6HBKSXV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0fgKxE0tvu2p3T4IGbCUB1O5FAdF_Kc4',
    appId: '1:694407226020:android:793c64df03eff40a9dbc31',
    messagingSenderId: '694407226020',
    projectId: 'college-notice-ee7ad',
    storageBucket: 'college-notice-ee7ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAE3ZooqfnbsM6BUg5yj2Tp22y3OQfxEg',
    appId: '1:694407226020:ios:1f9aaea751cd15b09dbc31',
    messagingSenderId: '694407226020',
    projectId: 'college-notice-ee7ad',
    storageBucket: 'college-notice-ee7ad.appspot.com',
    iosClientId: '694407226020-b1ei7lgssc8rv1mfptat4tj9o40t7roe.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeNotice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAE3ZooqfnbsM6BUg5yj2Tp22y3OQfxEg',
    appId: '1:694407226020:ios:e541fbe0b4a438949dbc31',
    messagingSenderId: '694407226020',
    projectId: 'college-notice-ee7ad',
    storageBucket: 'college-notice-ee7ad.appspot.com',
    iosClientId: '694407226020-r9o8lhh75grojdhko8r6hedu344a3336.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeNotice.RunnerTests',
  );
}
